###
# System configuration
###
server:
  port: 8090
  contextPath: /ticket-office-api
  error:
    whitelabel:
      enabled: false

###
# Spring Configuration
###
# Hibernate
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_office_api
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# MVC
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
###
# Security
####
security:
  sessions: never
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/ticket-office-oauth2/api/admin/user

###
# Swagger
###
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.json

###
# ZUUL
###
zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:8080/ticket-office-oauth2/api/admin/user
